apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-devops
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      containers:
        - name: hello-devops
          image: workkty/hello-devops:latest
          ports:
            - containerPort: 5000